INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Manuel', 'Landín', 'manu@mail.com', '1995-02-23', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Iago', 'Leirós', 'iago@mail.com', '1990-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Alejandro', 'Vázquez', 'alex@mail.com', '2000-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Ana', 'García', 'ana@mail.com', '2000-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Juan', 'Pérez', 'juan@mail.com', '2000-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Luis', 'Rodríguez', 'luis@mail.com', '2000-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('María', 'Martínez', 'maria@mail.com', '2000-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('José', 'Sánchez', 'jose@mail.com', '2000-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Pedro', 'González', 'pedro@mail.com', '2000-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Isabel', 'Díaz', 'isabel@mail.com', '2000-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Laura', 'López', 'laura@mail.com', '2000-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Miguel', 'Ruiz', 'miguel@mail.com', '2000-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Rosa', 'Hernández', 'rosa@mail.com', '2000-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Javier', 'Jiménez', 'javier@mail.com', '2001-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Carmen', 'Moreno', 'carmen@mail.com', '2002-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Adrián', 'Álvarez', 'adrian@mail.com', '2003-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Julia', 'Romero', 'julia@mail.com', '2004-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Alberto', 'Gutiérrez', 'alberto@mail.com', '2005-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Mercedes', 'Navarro', 'mercedes@mail.com', '2006-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Daniel', 'Torres', 'daniel@mail.com', '2007-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Raúl', 'Dominguez', 'raul@mail.com', '2008-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Elena', 'Vargas', 'elena@mail.com', '2009-01-01', '');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Carlos', 'Ramirez', 'carlos@mail.com', '2010-01-01', '');
INSERT INTO productos (nombre, precio, create_at) VALUES ('Television Sony OLED', 499, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Computadora ASUS ROG', 799, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Smartphone Samsung Galaxy S21', 800, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Amazon Echo Dot', 50, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('AirPods Pro', 199, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Reloj Apple Watch Series 6', 400, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Sony PlayStation 5', 499, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Microsoft Xbox Series X', 499, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Lenovo Laptop ThinkPad', 999, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Bose SoundLink Mini II', 199, NOW());
INSERT INTO facturas (descripcion, observacion, cliente_id, create_at) VALUES ('Factura equipos de oficina', null, 1, NOW());
INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES (1, 1, 1);
INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES (2, 1, 4);
INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES (1, 1, 5);
INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES (1, 1, 7);
INSERT INTO facturas (descripcion, observacion, cliente_id, create_at) VALUES ('Factura bicicleta', 'Observación importante', 1, NOW());
INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES (3, 2, 6);
INSERT INTO users (username, password, enabled) VALUES ('admin', '$2a$12$d6PSIyKdF6I1fXMIhfbZhelJrli3NHyy9sPB40ESWmfoRS0.Tjscm', 1);
INSERT INTO users (username, password, enabled) VALUES ('cliente', '$2a$12$VV39iqqVnKjeRx/mjWX72uu/Xjd/RQ.7mpKJGl6tFkqsvCtk6ka1u', 1);
INSERT INTO authorities (user_id, authority) value (1, 'ROLE_USER');
INSERT INTO authorities (user_id, authority) value (1, 'ROLE_ADMIN');
INSERT INTO authorities (user_id, authority) value (2, 'ROLE_USER');